# Generated by Django 6.1 on 2026-08-13 13:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('assessments', '0001_initial'),
        ('institutions', '0001_initial'),
        ('requests_app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationClassroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(blank=True, max_length=100, verbose_name='sala/local da aplicação')),
                ('notes', models.TextField(blank=True, verbose_name='orientações da turma')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='adicionada em')),
                ('applicators', models.ManyToManyField(blank=True, limit_choices_to={'is_active': True, 'role': 'APPLICATOR'}, related_name='assigned_application_classrooms', to=settings.AUTH_USER_MODEL, verbose_name='aplicadores')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_applications', to='academics.classroom', verbose_name='turma')),
            ],
            options={
                'verbose_name': 'turma da aplicação',
                'verbose_name_plural': 'turmas da aplicação',
                'ordering': ['classroom__school__name', 'classroom__grade__order', 'classroom__name'],
            },
        ),
        migrations.CreateModel(
            name='SimulationApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, editable=False, max_length=40, unique=True, verbose_name='código')),
                ('title', models.CharField(max_length=200, verbose_name='título da aplicação')),
                ('application_date', models.DateField(verbose_name='data da aplicação')),
                ('alternative_date', models.DateField(blank=True, null=True, verbose_name='data alternativa')),
                ('start_time', models.TimeField(blank=True, null=True, verbose_name='horário inicial')),
                ('end_time', models.TimeField(blank=True, null=True, verbose_name='horário final')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PREPARING', 'Em preparação'), ('READY', 'Pronta para aplicação'), ('IN_PROGRESS', 'Em aplicação'), ('PROCESSING', 'Processando gabaritos'), ('COMPLETED', 'Concluída'), ('CANCELLED', 'Cancelada')], default='DRAFT', max_length=20, verbose_name='situação')),
                ('general_instructions', models.TextField(blank=True, verbose_name='instruções gerais')),
                ('internal_notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='applications', to='assessments.assessment', verbose_name='prova')),
                ('coordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coordinated_applications', to=settings.AUTH_USER_MODEL, verbose_name='coordenador interno')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_applications', to='institutions.municipality', verbose_name='município')),
                ('simulation_request', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='application', to='requests_app.simulationrequest', verbose_name='solicitação de origem')),
            ],
            options={
                'verbose_name': 'aplicação de simulado',
                'verbose_name_plural': 'aplicações de simulados',
                'ordering': ['-application_date', 'title'],
            },
        ),
        migrations.CreateModel(
            name='Participation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='código seguro do cartão')),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='número sequencial')),
                ('status', models.CharField(choices=[('EXPECTED', 'Previsto'), ('PRESENT', 'Presente'), ('ABSENT', 'Ausente'), ('ANSWER_SHEET_RECEIVED', 'Gabarito recebido'), ('PROCESSED', 'Processado'), ('CANCELLED', 'Cancelado')], default='EXPECTED', max_length=30, verbose_name='situação')),
                ('notes', models.CharField(blank=True, max_length=255, verbose_name='observações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('application_classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='applications.applicationclassroom', verbose_name='turma da aplicação')),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participations', to='assessments.assessmentversion', verbose_name='versão da prova')),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_participations', to='academics.enrollment', verbose_name='matrícula')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='simulation_participations', to='academics.student', verbose_name='aluno')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participations', to='applications.simulationapplication', verbose_name='aplicação')),
            ],
            options={
                'verbose_name': 'participação',
                'verbose_name_plural': 'participações',
                'ordering': ['application', 'application_classroom', 'student__full_name'],
            },
        ),
        migrations.AddField(
            model_name='applicationclassroom',
            name='application',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_classrooms', to='applications.simulationapplication', verbose_name='aplicação'),
        ),
        migrations.AddIndex(
            model_name='simulationapplication',
            index=models.Index(fields=['code'], name='application_code_idx'),
        ),
        migrations.AddIndex(
            model_name='simulationapplication',
            index=models.Index(fields=['status', 'application_date'], name='application_status_date_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['card_code'], name='participation_card_idx'),
        ),
        migrations.AddIndex(
            model_name='participation',
            index=models.Index(fields=['application', 'status'], name='participation_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('application', 'student'), name='unique_student_by_application'),
        ),
        migrations.AddConstraint(
            model_name='participation',
            constraint=models.UniqueConstraint(fields=('application', 'sequence_number'), name='unique_sequence_by_application'),
        ),
        migrations.AddConstraint(
            model_name='applicationclassroom',
            constraint=models.UniqueConstraint(fields=('application', 'classroom'), name='unique_classroom_by_application'),
        ),
    ]
