# Generated by Django 6.1 on 2026-08-25 14:23

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
        ('assessments', '0002_alter_assessment_subject_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnswerSheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Em digitação'), ('ENTERED', 'Digitado'), ('VALIDATED', 'Validado'), ('PROCESSED', 'Processado'), ('REVIEW_REQUIRED', 'Revisão necessária')], default='DRAFT', max_length=30, verbose_name='situação')),
                ('input_method', models.CharField(choices=[('MANUAL', 'Digitação manual'), ('CAMERA', 'Leitura pela câmera'), ('IMPORT', 'Importação')], default='MANUAL', max_length=20, verbose_name='forma de lançamento')),
                ('question_count', models.PositiveSmallIntegerField(default=0, verbose_name='quantidade de questões')),
                ('answered_count', models.PositiveSmallIntegerField(default=0, verbose_name='questões respondidas')),
                ('blank_count', models.PositiveSmallIntegerField(default=0, verbose_name='questões em branco')),
                ('multiple_count', models.PositiveSmallIntegerField(default=0, verbose_name='marcações múltiplas')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name='acertos')),
                ('incorrect_count', models.PositiveSmallIntegerField(default=0, verbose_name='erros')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='nota')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='percentual')),
                ('entered_at', models.DateTimeField(blank=True, null=True, verbose_name='digitado em')),
                ('validated_at', models.DateTimeField(blank=True, null=True, verbose_name='validado em')),
                ('processed_at', models.DateTimeField(blank=True, null=True, verbose_name='processado em')),
                ('processing_message', models.CharField(blank=True, max_length=255, verbose_name='mensagem de processamento')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('entered_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entered_answer_sheets', to=settings.AUTH_USER_MODEL, verbose_name='digitado por')),
                ('participation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sheet', to='applications.participation', verbose_name='participação')),
                ('processed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_answer_sheets', to=settings.AUTH_USER_MODEL, verbose_name='processado por')),
                ('validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_answer_sheets', to=settings.AUTH_USER_MODEL, verbose_name='validado por')),
            ],
            options={
                'verbose_name': 'cartão lançado',
                'verbose_name_plural': 'cartões lançados',
                'ordering': ['-participation__application__application_date', 'participation__sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='AnswerEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marking_status', models.CharField(choices=[('SINGLE', 'Uma alternativa'), ('BLANK', 'Em branco'), ('MULTIPLE', 'Marcação múltipla')], default='BLANK', max_length=20, verbose_name='tipo de marcação')),
                ('selected_answer', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='alternativa marcada')),
                ('is_correct', models.BooleanField(blank=True, null=True, verbose_name='correta')),
                ('awarded_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='pontuação obtida')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answer_entries', to='assessments.question', verbose_name='questão')),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='applications.answersheet', verbose_name='cartão lançado')),
            ],
            options={
                'verbose_name': 'resposta lançada',
                'verbose_name_plural': 'respostas lançadas',
                'ordering': ['answer_sheet', 'question__number'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheetBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('COMPONENT', 'Componente curricular'), ('DESCRIPTOR', 'Habilidade/descritor')], max_length=20, verbose_name='dimensão')),
                ('key', models.CharField(max_length=100, verbose_name='identificador')),
                ('label', models.CharField(max_length=255, verbose_name='descrição')),
                ('question_count', models.PositiveSmallIntegerField(default=0, verbose_name='quantidade de questões')),
                ('answered_count', models.PositiveSmallIntegerField(default=0, verbose_name='respondidas')),
                ('correct_count', models.PositiveSmallIntegerField(default=0, verbose_name='acertos')),
                ('incorrect_count', models.PositiveSmallIntegerField(default=0, verbose_name='erros')),
                ('blank_count', models.PositiveSmallIntegerField(default=0, verbose_name='em branco')),
                ('multiple_count', models.PositiveSmallIntegerField(default=0, verbose_name='marcações múltiplas')),
                ('score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='pontuação')),
                ('maximum_score', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=8, verbose_name='pontuação máxima')),
                ('percentage', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=6, verbose_name='percentual')),
                ('answer_sheet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breakdowns', to='applications.answersheet', verbose_name='cartão lançado')),
            ],
            options={
                'verbose_name': 'resultado detalhado',
                'verbose_name_plural': 'resultados detalhados',
                'ordering': ['answer_sheet', 'dimension', 'key'],
            },
        ),
        migrations.AddIndex(
            model_name='answersheet',
            index=models.Index(fields=['status'], name='answer_sheet_status_idx'),
        ),
        migrations.AddIndex(
            model_name='answersheet',
            index=models.Index(fields=['processed_at'], name='answer_sheet_processed_idx'),
        ),
        migrations.AddIndex(
            model_name='answerentry',
            index=models.Index(fields=['answer_sheet', 'marking_status'], name='answer_entry_sheet_mark_idx'),
        ),
        migrations.AddIndex(
            model_name='answerentry',
            index=models.Index(fields=['question', 'is_correct'], name='ans_entry_question_result_idx'),
        ),
        migrations.AddConstraint(
            model_name='answerentry',
            constraint=models.UniqueConstraint(fields=('answer_sheet', 'question'), name='unique_question_by_answer_sheet'),
        ),
        migrations.AddIndex(
            model_name='answersheetbreakdown',
            index=models.Index(fields=['dimension', 'key'], name='answer_breakdown_dimension_idx'),
        ),
        migrations.AddConstraint(
            model_name='answersheetbreakdown',
            constraint=models.UniqueConstraint(fields=('answer_sheet', 'dimension', 'key'), name='unique_breakdown_by_answer_sheet'),
        ),
    ]
