# Generated by Django 6.1 on 2026-09-10 17:57

import applications.models
import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_answersheet_answerentry_answersheetbreakdown_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardSubmissionPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token de acesso')),
                ('contact_name', models.CharField(blank=True, max_length=200, verbose_name='responsável pelo envio')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='e-mail do responsável')),
                ('expires_at', models.DateTimeField(default=applications.models.default_card_portal_expiry, verbose_name='válido até')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('instructions', models.TextField(blank=True, verbose_name='orientações')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='card_submission_portal', to='applications.simulationapplication', verbose_name='aplicação')),
            ],
            options={
                'verbose_name': 'portal de envio de cartões',
                'verbose_name_plural': 'portais de envio de cartões',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AnswerSheetImageSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='código do envio')),
                ('image', models.ImageField(upload_to=applications.models.answer_sheet_image_path, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'webp'], message='Envie uma imagem JPG, PNG ou WEBP.'), applications.models.validate_answer_sheet_image], verbose_name='imagem do cartão-resposta')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('file_size', models.PositiveIntegerField(default=0, editable=False, verbose_name='tamanho do arquivo')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('UNDER_REVIEW', 'Em revisão'), ('ACCEPTED', 'Aceito'), ('REJECTED', 'Rejeitado')], default='RECEIVED', max_length=30, verbose_name='situação')),
                ('sender_name', models.CharField(blank=True, max_length=200, verbose_name='nome de quem enviou')),
                ('review_notes', models.TextField(blank=True, verbose_name='observações da revisão')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='image_submissions', to='applications.participation', verbose_name='participação')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='applications.cardsubmissionportal', verbose_name='portal')),
            ],
            options={
                'verbose_name': 'cartão fotografado',
                'verbose_name_plural': 'cartões fotografados',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='cardsubmissionportal',
            index=models.Index(fields=['token'], name='card_portal_token_idx'),
        ),
        migrations.AddIndex(
            model_name='cardsubmissionportal',
            index=models.Index(fields=['is_active', 'expires_at'], name='card_portal_access_idx'),
        ),
        migrations.AddIndex(
            model_name='answersheetimagesubmission',
            index=models.Index(fields=['status', 'created_at'], name='sheet_upload_status_idx'),
        ),
        migrations.AddIndex(
            model_name='answersheetimagesubmission',
            index=models.Index(fields=['submission_code'], name='sheet_upload_code_idx'),
        ),
    ]
