# Generated by Django 6.1 on 2026-09-14 17:07

import django.db.models.deletion
import uuid
from django.db import migrations, models

def create_initial_discipline_cards(
    apps,
    schema_editor,
):
    SimulationApplication = apps.get_model(
        "applications",
        "SimulationApplication",
    )
    Participation = apps.get_model(
        "applications",
        "Participation",
    )
    ApplicationAssessment = apps.get_model(
        "applications",
        "ApplicationAssessment",
    )
    ParticipationCard = apps.get_model(
        "applications",
        "ParticipationCard",
    )

    assessment_links = {}

    applications = (
        SimulationApplication.objects
        .all()
        .order_by("pk")
    )

    for application in applications.iterator():
        link = ApplicationAssessment.objects.create(
            application_id=application.pk,
            assessment_id=application.assessment_id,
            order=1,
            is_active=True,
        )

        assessment_links[
            application.pk
        ] = link.pk

    status_mapping = {
        "EXPECTED": "EXPECTED",
        "PRESENT": "EXPECTED",
        "ABSENT": "CANCELLED",
        "ANSWER_SHEET_RECEIVED": "RECEIVED",
        "PROCESSED": "PROCESSED",
        "CANCELLED": "CANCELLED",
    }

    cards = []

    participations = (
        Participation.objects
        .all()
        .order_by("pk")
    )

    for participation in participations.iterator():
        cards.append(
            ParticipationCard(
                participation_id=participation.pk,
                application_assessment_id=(
                    assessment_links[
                        participation.application_id
                    ]
                ),
                assessment_version_id=(
                    participation.assessment_version_id
                ),
                card_code=participation.card_code,
                sequence_number=(
                    participation.sequence_number
                ),
                status=status_mapping.get(
                    participation.status,
                    "EXPECTED",
                ),
            )
        )

        if len(cards) >= 500:
            ParticipationCard.objects.bulk_create(
                cards,
                batch_size=500,
            )
            cards = []

    if cards:
        ParticipationCard.objects.bulk_create(
            cards,
            batch_size=500,
        )


def remove_initial_discipline_cards(
    apps,
    schema_editor,
):
    ParticipationCard = apps.get_model(
        "applications",
        "ParticipationCard",
    )
    ApplicationAssessment = apps.get_model(
        "applications",
        "ApplicationAssessment",
    )

    ParticipationCard.objects.all().delete()
    ApplicationAssessment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_cardsubmissionportal_answersheetimagesubmission_and_more'),
        ('assessments', '0002_alter_assessment_subject_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='adicionada em')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='application_assessments', to='applications.simulationapplication', verbose_name='aplicação')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='application_links', to='assessments.assessment', verbose_name='prova')),
            ],
            options={
                'verbose_name': 'prova da aplicação',
                'verbose_name_plural': 'provas da aplicação',
                'ordering': ['application', 'order', 'assessment__title'],
            },
        ),
        migrations.CreateModel(
            name='ParticipationCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_code', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='código seguro do cartão')),
                ('sequence_number', models.PositiveIntegerField(blank=True, null=True, verbose_name='número sequencial')),
                ('status', models.CharField(choices=[('EXPECTED', 'Aguardando cartão'), ('RECEIVED', 'Cartão recebido'), ('PROCESSED', 'Processado'), ('CANCELLED', 'Cancelado')], default='EXPECTED', max_length=20, verbose_name='situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('application_assessment', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_cards', to='applications.applicationassessment', verbose_name='prova da aplicação')),
                ('assessment_version', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='participation_cards', to='assessments.assessmentversion', verbose_name='versão da prova')),
                ('participation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='discipline_cards', to='applications.participation', verbose_name='participação')),
            ],
            options={
                'verbose_name': 'cartão disciplinar',
                'verbose_name_plural': 'cartões disciplinares',
                'ordering': ['participation', 'application_assessment__order'],
            },
        ),
        migrations.RunPython(
            create_initial_discipline_cards,
            remove_initial_discipline_cards,
        ),
        migrations.AddIndex(
            model_name='applicationassessment',
            index=models.Index(fields=['application', 'is_active'], name='app_assessment_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='applicationassessment',
            constraint=models.UniqueConstraint(fields=('application', 'assessment'), name='unique_assessment_by_application'),
        ),
        migrations.AddConstraint(
            model_name='applicationassessment',
            constraint=models.UniqueConstraint(fields=('application', 'order'), name='unique_assessment_order_by_app'),
        ),
        migrations.AddIndex(
            model_name='participationcard',
            index=models.Index(fields=['card_code'], name='part_card_code_idx'),
        ),
        migrations.AddIndex(
            model_name='participationcard',
            index=models.Index(fields=['application_assessment', 'status'], name='part_card_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='participationcard',
            constraint=models.UniqueConstraint(fields=('participation', 'application_assessment'), name='unique_card_by_participation_assessment'),
        ),
        migrations.AddConstraint(
            model_name='participationcard',
            constraint=models.UniqueConstraint(fields=('application_assessment', 'sequence_number'), name='unique_card_sequence_by_assessment'),
        ),
    ]
