# Generated by Django 6.1 on 2026-09-14 18:22

import django.db.models.deletion
from django.db import migrations, models

def link_existing_submissions_to_cards(
    apps,
    schema_editor,
):
    AnswerSheetImageSubmission = apps.get_model(
        "applications",
        "AnswerSheetImageSubmission",
    )
    ParticipationCard = apps.get_model(
        "applications",
        "ParticipationCard",
    )

    submissions = (
        AnswerSheetImageSubmission.objects
        .filter(
            participation_card__isnull=True,
        )
        .select_related(
            "participation",
        )
        .order_by("pk")
    )

    for submission in submissions.iterator():
        card = (
            ParticipationCard.objects
            .filter(
                participation_id=(
                    submission.participation_id
                ),
                card_code=(
                    submission.participation.card_code
                ),
            )
            .first()
        )

        if card is None:
            card = (
                ParticipationCard.objects
                .filter(
                    participation_id=(
                        submission.participation_id
                    ),
                )
                .order_by(
                    "application_assessment__order",
                    "pk",
                )
                .first()
            )

        if card is None:
            raise RuntimeError(
                (
                    "Não foi encontrado cartão disciplinar "
                    f"para o envio {submission.pk}."
                )
            )

        submission.participation_card_id = (
            card.pk
        )
        submission.save(
            update_fields=[
                "participation_card",
            ]
        )


def unlink_existing_submissions_from_cards(
    apps,
    schema_editor,
):
    AnswerSheetImageSubmission = apps.get_model(
        "applications",
        "AnswerSheetImageSubmission",
    )

    AnswerSheetImageSubmission.objects.update(
        participation_card=None,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applicationassessment_participationcard_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheetimagesubmission',
            name='participation_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='image_submissions', to='applications.participationcard', verbose_name='cartão disciplinar'),
        ),
        migrations.RunPython(
            link_existing_submissions_to_cards,
            unlink_existing_submissions_from_cards,
        ),
    ]
