# Generated by Django 6.1 on 2026-09-14 22:16

import django.db.models.deletion
from django.db import migrations, models

def link_existing_answer_sheets(
    apps,
    schema_editor,
):
    AnswerSheet = apps.get_model(
        "applications",
        "AnswerSheet",
    )
    ParticipationCard = apps.get_model(
        "applications",
        "ParticipationCard",
    )

    answer_sheets = (
        AnswerSheet.objects
        .select_related("participation")
        .filter(participation_card__isnull=True)
        .iterator()
    )

    for answer_sheet in answer_sheets:
        participation = answer_sheet.participation

        participation_card = (
            ParticipationCard.objects.filter(
                participation_id=participation.pk,
                card_code=participation.card_code,
            )
            .order_by(
                "application_assessment__order",
                "pk",
            )
            .first()
        )

        if participation_card is None:
            participation_card = (
                ParticipationCard.objects.filter(
                    participation_id=participation.pk,
                    assessment_version_id=(
                        participation.assessment_version_id
                    ),
                )
                .order_by(
                    "application_assessment__order",
                    "pk",
                )
                .first()
            )

        if participation_card is None:
            raise RuntimeError(
                (
                    "Não foi encontrado cartão disciplinar "
                    f"para a participação {participation.pk}."
                )
            )

        answer_sheet.participation_card_id = (
            participation_card.pk
        )
        answer_sheet.save(
            update_fields=[
                "participation_card",
            ]
        )


def unlink_existing_answer_sheets(
    apps,
    schema_editor,
):
    AnswerSheet = apps.get_model(
        "applications",
        "AnswerSheet",
    )

    AnswerSheet.objects.update(
        participation_card=None,
    )

class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0005_answersheetimagesubmission_participation_card'),
    ]

    operations = [
        migrations.AddField(
            model_name='answersheet',
            name='participation_card',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='answer_sheet', to='applications.participationcard', verbose_name='cartão disciplinar'),
        ),
        migrations.RunPython(
            link_existing_answer_sheets,
            unlink_existing_answer_sheets,
        ),
    ]
