# Generated by Django 6.1 on 2026-08-12 19:16

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='título')),
                ('code', models.CharField(help_text='Exemplo: SIM-MAT-9ANO-2026.', max_length=50, unique=True, verbose_name='código')),
                ('description', models.TextField(blank=True, verbose_name='descrição')),
                ('instructions', models.TextField(blank=True, verbose_name='instruções')),
                ('source_file', models.FileField(blank=True, upload_to='assessments/source_files/%Y/%m/', verbose_name='arquivo da prova')),
                ('status', models.CharField(choices=[('DRAFT', 'Rascunho'), ('PUBLISHED', 'Publicada'), ('CLOSED', 'Encerrada')], default='DRAFT', max_length=20, verbose_name='situação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.academicyear', verbose_name='ano letivo')),
                ('grades', models.ManyToManyField(related_name='assessments', to='academics.grade', verbose_name='séries/anos')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.subject', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'prova',
                'verbose_name_plural': 'provas',
                'ordering': ['-academic_year__year', 'title'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default='A', help_text='Exemplo: A, B ou C.', max_length=10, verbose_name='versão')),
                ('question_count', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade de questões')),
                ('option_count', models.PositiveSmallIntegerField(default=5, help_text='Use 4 para A–D ou 5 para A–E.', validators=[django.core.validators.MinValueValidator(2)], verbose_name='alternativas por questão')),
                ('total_score', models.DecimalField(decimal_places=2, default=Decimal('10.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='nota máxima')),
                ('source_file', models.FileField(blank=True, upload_to='assessments/versions/%Y/%m/', verbose_name='arquivo específico da versão')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='assessments.assessment', verbose_name='prova')),
            ],
            options={
                'verbose_name': 'versão da prova',
                'verbose_name_plural': 'versões das provas',
                'ordering': ['assessment', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='número')),
                ('statement', models.TextField(blank=True, help_text='Opcional no modo rápido. A prova pode permanecer apenas em PDF.', verbose_name='enunciado')),
                ('descriptor_code', models.CharField(blank=True, max_length=50, verbose_name='código da habilidade/descritor')),
                ('descriptor', models.CharField(blank=True, max_length=255, verbose_name='habilidade/descritor')),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], max_length=1, verbose_name='resposta correta')),
                ('weight', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='peso')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.assessmentversion', verbose_name='versão da prova')),
            ],
            options={
                'verbose_name': 'questão',
                'verbose_name_plural': 'questões',
                'ordering': ['version', 'number'],
            },
        ),
        migrations.AddConstraint(
            model_name='assessmentversion',
            constraint=models.UniqueConstraint(fields=('assessment', 'code'), name='unique_version_by_assessment'),
        ),
        migrations.AddConstraint(
            model_name='question',
            constraint=models.UniqueConstraint(fields=('version', 'number'), name='unique_question_number_by_version'),
        ),
    ]
