# Generated by Django 6.1 on 2026-08-18 14:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assessment',
            name='subject',
            field=models.ForeignKey(blank=True, help_text='Utilizado em provas de uma única disciplina. Para simulados multidisciplinares, use os componentes.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='assessments', to='academics.subject', verbose_name='disciplina principal'),
        ),
        migrations.AlterField(
            model_name='question',
            name='correct_answer',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E')], help_text='Pode permanecer vazia enquanto o gabarito estiver aguardando confirmação pedagógica.', max_length=1, verbose_name='resposta correta'),
        ),
        migrations.CreateModel(
            name='AssessmentComponent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Exemplo: PORT ou MAT.', max_length=30, verbose_name='código')),
                ('title', models.CharField(help_text='Exemplo: Língua Portuguesa.', max_length=150, verbose_name='título')),
                ('start_question', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='questão inicial')),
                ('end_question', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='questão final')),
                ('order', models.PositiveSmallIntegerField(default=1, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='components', to='assessments.assessment', verbose_name='prova')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_components', to='academics.subject', verbose_name='disciplina')),
            ],
            options={
                'verbose_name': 'componente da prova',
                'verbose_name_plural': 'componentes da prova',
                'ordering': ['assessment', 'order', 'start_question'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='component',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='questions', to='assessments.assessmentcomponent', verbose_name='componente curricular'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcomponent',
            constraint=models.UniqueConstraint(fields=('assessment', 'code'), name='unique_component_code_by_assessment'),
        ),
        migrations.AddConstraint(
            model_name='assessmentcomponent',
            constraint=models.UniqueConstraint(fields=('assessment', 'order'), name='unique_component_order_by_assessment'),
        ),
    ]
