# Generated by Django 6.1 on 2026-08-13 00:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(blank=True, editable=False, max_length=30, unique=True, verbose_name='protocolo')),
                ('requester_name', models.CharField(max_length=200, verbose_name='nome do responsável')),
                ('requester_role', models.CharField(max_length=150, verbose_name='cargo ou função')),
                ('requester_email', models.EmailField(max_length=254, verbose_name='e-mail institucional')),
                ('requester_phone', models.CharField(max_length=20, verbose_name='telefone/WhatsApp')),
                ('requester_institution', models.CharField(max_length=200, verbose_name='instituição solicitante')),
                ('state', models.CharField(default='CE', max_length=2, verbose_name='estado')),
                ('municipality_name', models.CharField(max_length=150, verbose_name='município')),
                ('request_scope', models.CharField(choices=[('MUNICIPAL_NETWORK', 'Rede municipal'), ('SINGLE_SCHOOL', 'Uma escola'), ('SCHOOL_GROUP', 'Conjunto de escolas'), ('SPECIFIC_CLASSROOMS', 'Turmas específicas')], max_length=30, verbose_name='abrangência')),
                ('education_department_name', models.CharField(blank=True, max_length=200, verbose_name='Secretaria de Educação')),
                ('school_name', models.CharField(blank=True, max_length=200, verbose_name='escola de referência')),
                ('school_inep_code', models.CharField(blank=True, max_length=20, verbose_name='código INEP')),
                ('preferred_date', models.DateField(verbose_name='data desejada')),
                ('alternative_date', models.DateField(blank=True, null=True, verbose_name='data alternativa')),
                ('academic_year', models.PositiveIntegerField(default=2026, verbose_name='ano letivo')),
                ('estimated_school_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade estimada de escolas')),
                ('estimated_classroom_count', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade estimada de turmas')),
                ('estimated_student_count', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade estimada de alunos')),
                ('estimated_question_count', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='quantidade estimada de questões')),
                ('objective', models.CharField(choices=[('INITIAL_DIAGNOSIS', 'Diagnóstico inicial'), ('MONITORING', 'Acompanhamento da aprendizagem'), ('FINAL_ASSESSMENT', 'Avaliação final'), ('EXTERNAL_PREPARATION', 'Preparação para avaliação externa'), ('OTHER', 'Outro')], max_length=30, verbose_name='objetivo da avaliação')),
                ('objective_details', models.CharField(blank=True, max_length=255, verbose_name='detalhamento do objetivo')),
                ('assessment_source', models.CharField(choices=[('PUBLISHER', 'Prova fornecida pela Editora Dinâmica'), ('REQUESTER', 'Prova fornecida pela instituição solicitante'), ('TO_DEFINE', 'A definir')], default='TO_DEFINE', max_length=20, verbose_name='origem da prova')),
                ('print_responsibility', models.CharField(choices=[('PUBLISHER', 'Editora Dinâmica'), ('REQUESTER', 'Município ou escola'), ('TO_DEFINE', 'A definir')], default='TO_DEFINE', max_length=20, verbose_name='responsável pela impressão')),
                ('applicator_responsibility', models.CharField(choices=[('PUBLISHER', 'Aplicadores da Editora Dinâmica'), ('REQUESTER', 'Aplicadores locais'), ('SHARED', 'Operação compartilhada'), ('TO_DEFINE', 'A definir')], default='TO_DEFINE', max_length=20, verbose_name='responsável pela aplicação')),
                ('has_scanning_devices', models.BooleanField(default=False, verbose_name='possui celulares para digitalização')),
                ('internet_quality', models.CharField(choices=[('GOOD', 'Boa'), ('LIMITED', 'Limitada'), ('UNAVAILABLE', 'Sem internet'), ('UNKNOWN', 'Não informado')], default='UNKNOWN', max_length=20, verbose_name='qualidade da internet')),
                ('notes', models.TextField(blank=True, verbose_name='observações')),
                ('privacy_accepted', models.BooleanField(default=False, verbose_name='aceite institucional e de privacidade')),
                ('privacy_accepted_at', models.DateTimeField(blank=True, editable=False, null=True, verbose_name='aceite realizado em')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebida'), ('UNDER_REVIEW', 'Em análise'), ('WAITING_INFORMATION', 'Aguardando informações'), ('APPROVED', 'Aprovada'), ('PREPARING_DATA', 'Preparando dados'), ('APPLICATION_CREATED', 'Aplicação criada'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Concluída')], default='RECEIVED', max_length=30, verbose_name='situação')),
                ('internal_notes', models.TextField(blank=True, verbose_name='observações internas')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebida em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_simulation_requests', to=settings.AUTH_USER_MODEL, verbose_name='responsável interno')),
                ('grades', models.ManyToManyField(related_name='simulation_requests', to='academics.grade', verbose_name='séries/anos')),
                ('subjects', models.ManyToManyField(related_name='simulation_requests', to='academics.subject', verbose_name='disciplinas')),
            ],
            options={
                'verbose_name': 'solicitação de simulado',
                'verbose_name_plural': 'solicitações de simulados',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['protocol'], name='request_protocol_idx'), models.Index(fields=['status', 'created_at'], name='request_status_date_idx'), models.Index(fields=['municipality_name'], name='request_municipality_idx')],
            },
        ),
    ]
