# Generated by Django 6.1 on 2026-08-18 19:27

import data_portal.models
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPreparationPortal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='token')),
                ('contact_name', models.CharField(max_length=200, verbose_name='responsável institucional')),
                ('contact_email', models.EmailField(max_length=254, verbose_name='e-mail do responsável')),
                ('expires_at', models.DateTimeField(default=data_portal.models.default_portal_expiry, verbose_name='válido até')),
                ('status', models.CharField(choices=[('OPEN', 'Aguardando dados'), ('IN_PROGRESS', 'Em preenchimento'), ('FILE_RECEIVED', 'Arquivo recebido'), ('HAS_ERRORS', 'Com pendências'), ('READY', 'Dados validados'), ('SUBMITTED', 'Enviado para revisão'), ('IMPORTED', 'Importado'), ('CLOSED', 'Encerrado')], default='OPEN', max_length=30, verbose_name='situação')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('submitted_at', models.DateTimeField(blank=True, null=True, verbose_name='enviado para revisão em')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='importado em')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('application', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='data_portal', to='applications.simulationapplication', verbose_name='aplicação')),
            ],
            options={
                'verbose_name': 'portal de preparação',
                'verbose_name_plural': 'portais de preparação',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SpreadsheetUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='private/student_imports/%Y/%m/', validators=[data_portal.models.validate_spreadsheet_file], verbose_name='planilha')),
                ('original_name', models.CharField(blank=True, max_length=255, verbose_name='nome original')),
                ('status', models.CharField(choices=[('RECEIVED', 'Recebido'), ('VALID', 'Válido'), ('INVALID', 'Com erros'), ('IMPORTED', 'Importado')], default='RECEIVED', max_length=20, verbose_name='situação')),
                ('school_count', models.PositiveIntegerField(default=0, verbose_name='escolas encontradas')),
                ('classroom_count', models.PositiveIntegerField(default=0, verbose_name='turmas encontradas')),
                ('student_count', models.PositiveIntegerField(default=0, verbose_name='alunos encontrados')),
                ('error_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de erros')),
                ('warning_count', models.PositiveIntegerField(default=0, verbose_name='quantidade de avisos')),
                ('validation_report', models.JSONField(blank=True, default=dict, verbose_name='relatório da validação')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='recebido em')),
                ('imported_at', models.DateTimeField(blank=True, null=True, verbose_name='importado em')),
                ('portal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploads', to='data_portal.datapreparationportal', verbose_name='portal')),
            ],
            options={
                'verbose_name': 'planilha recebida',
                'verbose_name_plural': 'planilhas recebidas',
                'ordering': ['-created_at'],
            },
        ),
    ]
