# Generated by Django 6.1 on 2026-08-11 19:03

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('institutions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MinValueValidator(2020)], verbose_name='ano')),
                ('is_current', models.BooleanField(default=False, verbose_name='ano atual')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'ano letivo',
                'verbose_name_plural': 'anos letivos',
                'ordering': ['-year'],
            },
        ),
        migrations.CreateModel(
            name='EducationStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'etapa de ensino',
                'verbose_name_plural': 'etapas de ensino',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
            ],
            options={
                'verbose_name': 'disciplina',
                'verbose_name_plural': 'disciplinas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Grade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='nome')),
                ('code', models.CharField(max_length=30, unique=True, verbose_name='código')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='ordem')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('stage', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='grades', to='academics.educationstage', verbose_name='etapa de ensino')),
            ],
            options={
                'verbose_name': 'série/ano',
                'verbose_name_plural': 'séries/anos',
                'ordering': ['stage__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Classroom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Exemplo: A, B, Única ou 901.', max_length=50, verbose_name='identificação da turma')),
                ('shift', models.CharField(choices=[('MORNING', 'Manhã'), ('AFTERNOON', 'Tarde'), ('EVENING', 'Noite'), ('FULL_TIME', 'Integral')], default='MORNING', max_length=20, verbose_name='turno')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('academic_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.academicyear', verbose_name='ano letivo')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='institutions.school', verbose_name='escola')),
                ('grade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='classrooms', to='academics.grade', verbose_name='série/ano')),
                ('subjects', models.ManyToManyField(blank=True, related_name='classrooms', to='academics.subject', verbose_name='disciplinas')),
            ],
            options={
                'verbose_name': 'turma',
                'verbose_name_plural': 'turmas',
                'ordering': ['-academic_year__year', 'school__name', 'grade__order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_code', models.CharField(max_length=50, verbose_name='matrícula')),
                ('full_name', models.CharField(max_length=200, verbose_name='nome completo')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='data de nascimento')),
                ('responsible_name', models.CharField(blank=True, max_length=200, verbose_name='nome do responsável')),
                ('responsible_phone', models.CharField(blank=True, max_length=20, verbose_name='telefone do responsável')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='students', to='institutions.school', verbose_name='escola')),
            ],
            options={
                'verbose_name': 'aluno',
                'verbose_name_plural': 'alunos',
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('TRANSFERRED', 'Transferido'), ('CANCELLED', 'Cancelada'), ('COMPLETED', 'Concluída')], default='ACTIVE', max_length=20, verbose_name='situação')),
                ('enrollment_date', models.DateField(blank=True, null=True, verbose_name='data da matrícula')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.classroom', verbose_name='turma')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='enrollments', to='academics.student', verbose_name='aluno')),
            ],
            options={
                'verbose_name': 'matrícula',
                'verbose_name_plural': 'matrículas',
                'ordering': ['-classroom__academic_year__year', 'student__full_name'],
            },
        ),
        migrations.AddConstraint(
            model_name='grade',
            constraint=models.UniqueConstraint(fields=('stage', 'name'), name='unique_grade_by_stage'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['full_name'], name='student_name_idx'),
        ),
        migrations.AddIndex(
            model_name='student',
            index=models.Index(fields=['registration_code'], name='student_registration_idx'),
        ),
        migrations.AddConstraint(
            model_name='student',
            constraint=models.UniqueConstraint(fields=('school', 'registration_code'), name='unique_student_registration_by_school'),
        ),
        migrations.AddConstraint(
            model_name='enrollment',
            constraint=models.UniqueConstraint(fields=('student', 'classroom'), name='unique_student_classroom_enrollment'),
        ),
        migrations.AddConstraint(
            model_name='classroom',
            constraint=models.UniqueConstraint(fields=('school', 'academic_year', 'grade', 'name', 'shift'), name='unique_classroom_configuration'),
        ),
    ]
