# Generated by Django 6.1 on 2026-08-11 14:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='nome')),
                ('state', models.CharField(default='CE', max_length=2, verbose_name='estado')),
                ('ibge_code', models.CharField(blank=True, max_length=10, verbose_name='código IBGE')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criado em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizado em')),
            ],
            options={
                'verbose_name': 'município',
                'verbose_name_plural': 'municípios',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('name', 'state'), name='unique_municipality_by_state')],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='nome')),
                ('inep_code', models.CharField(blank=True, max_length=20, verbose_name='código INEP')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='endereço')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativa')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='criada em')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='atualizada em')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='schools', to='institutions.municipality', verbose_name='município')),
            ],
            options={
                'verbose_name': 'escola',
                'verbose_name_plural': 'escolas',
                'ordering': ['municipality__name', 'name'],
                'constraints': [models.UniqueConstraint(fields=('municipality', 'name'), name='unique_school_by_municipality')],
            },
        ),
    ]
